Get http://localhost:8000/products/ HTTP/1.1

###

PUT http://localhost:8000/products/1/ HTTP/1.1
Content-Type: application/json

{
    "name": "smart tv6",
    "description": "A new product description",
    "price": 19.99,
    "stock": 5
}

###

GET  http://localhost:8000/products/1/ HTTP/1.1

###

DELETE   http://localhost:8000/products/1/ HTTP/1.1

###
POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDg5MjQ3LCJpYXQiOjE3NDYwODg5NDcsImp0aSI6ImQ2NjEzYWNkYjdiZDQyMzZiMGFkNjE3ZWY5OWMyZWVjIiwidXNlcl9pZCI6MX0.l0pQWu_6vYjz5iyi1OQ3y8Eo5smyKiDpnTMP0Y9TOes

{
    "name": "smart tv2",
    "price": 19.99,
    "description": "A new product description",
    "stock": 5
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "emad",
    "password": "test"
}

###

Get http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDg5MjQ3LCJpYXQiOjE3NDYwODg5NDcsImp0aSI6ImQ2NjEzYWNkYjdiZDQyMzZiMGFkNjE3ZWY5OWMyZWVjIiwidXNlcl9pZCI6MX0.l0pQWu_6vYjz5iyi1OQ3y8Eo5smyKiDpnTMP0Y9TOes

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NjE3Njg0MCwiaWF0IjoxNzQ2MDkwNDQwLCJqdGkiOiJkNDA5YjVmMjllY2I0ZGYyOTVjMWY3Nzg5ZDFkYzdlMyIsInVzZXJfaWQiOjF9.sbbaM08JEUF8vZZJ654WoBhJzYyLXmW91OW4nb_EqE8"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDAyNzU0LCJpYXQiOjE3NDc0MDI0NTQsImp0aSI6IjczYTZmOWQ0M2I4OTRlNjM4NjZjZjdlOWM4YjY0YmExIiwidXNlcl9pZCI6M30.WPXSGtMIQU3zc471HpFk1HipA245PqkR4Prkva62ckQ

###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDAyNzU0LCJpYXQiOjE3NDc0MDI0NTQsImp0aSI6IjczYTZmOWQ0M2I4OTRlNjM4NjZjZjdlOWM4YjY0YmExIiwidXNlcl9pZCI6M30.WPXSGtMIQU3zc471HpFk1HipA245PqkR4Prkva62ckQ

    {
        "status": "Pending",
    "user": 1,
    "items":[
        {
            "product": 1,
            "quantity": 2
        },
        {
            "product": 2,
            "quantity": 1
        }
    ]
    }
